### ISSUE TITLE
Lichess sends invalid move

### ISSUE THREAD

**Issue by Torom** [Torom/BotLi#151] opened 2023-11-22 08:22 UTC
Created from @IbaiBuR

This is the error I got during the game:

```
Exception in thread Thread-913:

Traceback (most recent call last):

  File "/usr/local/lib/python3.12/threading.py", line 1052, in _bootstrap_inner

    self.run()

  File "/game.py", line 71, in run

    updated = self.lichess_game.update(event)

              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/lichess_game.py", line 88, in update

    self.board.push(chess.Move.from_uci(moves[-1]))

  File "/usr/local/lib/python3.12/site-packages/chess/__init__.py", line 2259, in push

    assert piece_type is not None, f"push() expects move to be pseudo-legal, but got {move} in {self.board_fen()}"

AssertionError: push() expects move to be pseudo-legal, but got a1a4 in 3n2k1/2p2ppp/1p6/8/r2BP3/2P2PP1/5K2/5R2
```
Along with the error,  the engine made an stupid move giving up a rook for free (I dont even know why), so, afterwards,  I checked btop (similar to htop) because the server's CPU usage stagnated for some reason, and I saw this:

![Screenshot from 2023-11-22 08-49-06](https://github.com/Torom/BotLi/assets/64355006/f33d7b9b-23ef-40b3-b3fb-fa89e53570a5)

So 2 instances of the engine were runninng at once, for some unknown reason. Even if I am using my own stockfish-derived engine, I do not think the error is related to that, because it never happened to me before.

Some insights about the environment the bot is running in:

- OS: Ubuntu 22.04LTS
- CPU: AMD EPYC 7282, 2 threads used of 4 available
- Dockerized, using python:3.12 base image
- The config file:

```yaml
token: ""         

engines:
  bullet:
    dir: "./engines"
    name: "BlackHole"
    ponder: true
    use_syzygy: true
    silence_stderr: true
    uci_options:
      Threads: 2
      Hash: 256
      Move Overhead: 500
      Experience Book: true
  blitz:                                 
    dir: "./engines"                     
    name: "BlackHole"                    
    ponder: true                         
    use_syzygy: true                     
    silence_stderr: true                 
    uci_options:                         
      Threads: 2                         
      Hash: 256                          
      Move Overhead: 750                 
      Experience Book: true
  rapid:                                 
    dir: "./engines"                     
    name: "BlackHole"                    
    ponder: true                         
    use_syzygy: true                     
    silence_stderr: true                 
    uci_options:                         
      Threads: 2                         
      Hash: 256                          
      Move Overhead: 850
  classical:                             
    dir: "./engines"                      
    name: "BlackHole"                     
    ponder: true                          
    use_syzygy: true                      
    silence_stderr: true                  
    uci_options:                          
      Threads: 2                          
      Hash: 256                           
      Move Overhead: 1000  

syzygy:
  enabled: true                           
  paths:                                  
    - "./engines/syzygy"
  max_pieces: 5                           
  instant_play: true                      

gaviota:
  enabled: false                          
  paths:                                  
    - "/path/to/gaviota"
  max_pieces: 5                           

opening_books:
  enabled: true                           
  priority: 400                           
  books:
    bullet_white:
      selection: weighted_random          
      names:
online_moves:
  opening_explorer:
    enabled: false                      
    priority: 300                       
    use_for_variants: false             
    min_time: 20                        
    timeout: 5                          
    min_games: 5                        
    only_with_wins: false               
    selection: "performance"            
    anti: false                         
#   max_depth: 16                       
#   max_moves: 1                        
  lichess_cloud:
    enabled: false                      
    priority: 200                       
    only_without_book: false            
    min_eval_depth: 10                  
    min_time: 20                        
    timeout: 5                          
#   max_depth: 16                       
#   max_moves: 1                        
  chessdb:
    enabled: false                      
    priority: 100                       
    min_eval_depth: 10                  
    min_time: 20                        
    timeout: 5                          
#   max_depth: 16                       
#   max_moves: 1                        
  online_egtb:
    enabled: true                       
    min_time: 10                        
    timeout: 2                          

offer_draw:
  enabled: true                         
  score: 10                             
  consecutive_moves: 10                 
  min_game_length: 35                   

resign:
  enabled: false                        
  score: -1000                          
  consecutive_moves: 5                  

move_overhead_multiplier: 1.1           

challenge:                               
  concurrency: 1                         
  bullet_with_increment_only: true       
# min_increment: 1                       
  max_increment: 5                       
  min_initial: 60                        
  max_initial: 1800                      
  variants:                              
    - standard
#   - chess960
#   - fromPosition
#   - antichess
#   - atomic
#   - crazyhouse
#   - horde
#   - kingOfTheHill
#   - racingKings
#   - threeCheck
  time_controls:
    - bullet
    - blitz
    - rapid
    - classical
  bot_modes:                              
    - casual                              
    - rated                               
  human_modes:                            
#   - casual                              
#   - rated                               

matchmaking:
  delay: 90                               
  timeout: 30                             
  types:  
    bullet_1:                              
      tc: 1+1                             
      rated: true                         
      variant: standard                   
      weight: 10                          
      multiplier: 20                      
      max_rating_diff: 400
    bullet_2:                              
      tc: 2+1                             
      rated: true                         
      variant: standard                   
      weight: 10                          
      multiplier: 20                      
      max_rating_diff: 400
    blitz_1:                              
      tc:  3+2                           
      rated: true                         
      variant: standard                   
      weight: 10                          
      multiplier: 20                      
      max_rating_diff: 400
    blitz_2:                              
      tc:  5+0                           
      rated: true                         
      variant: standard                   
      weight: 15                          
      multiplier: 20                      
      max_rating_diff: 400
    blitz_3:                              
      tc:  5+3                           
      rated: true                         
      variant: standard                   
      weight: 10                          
      multiplier: 20                      
      max_rating_diff: 400
    rapid_1:                              
      tc:  5+5                           
      rated: true                         
      variant: standard                   
      weight: 10                          
      multiplier: 20                      
      max_rating_diff: 400
    rapid_2:                              
      tc:  8+2                           
      rated: true                         
      variant: standard                   
      weight: 10                          
      multiplier: 20                      
      max_rating_diff: 400
    rapid_3:                              
      tc:  10+3                           
      rated: true                         
      variant: standard                   
      weight: 10                          
      multiplier: 20                      
      max_rating_diff: 400
    classical_1:                              
      tc:  25+1                           
      rated: true                         
      variant: standard                   
      weight: 15                          
      multiplier: 20                      
      max_rating_diff: 400
      
messages:
  greeting: "Hey, I'm {me} running {engine}. Good luck! Type !help for a list of commands." 
  goodbye: "Good game {opponent} , see you next time."                                      
  greeting_spectators: "Hey I'm {me} running {engine}. Type !help for a list of commands." 
  goodbye_spectators: "Thanks for watching {me} vs {opponent}!"                             
```

The book part is missing since I prefer to keep it private and also the blacklist/whitelist one.

**Comment by Torom** [comment] 2023-11-22 08:26
I have created a new issue because although the result is similar, the cause is completely different.

It looks like the local board does not match with Lichess' board or Lichess sent an invalid move for some other reason.

@IbaiBuR Can you please post the link to the game.

**Comment by IbaiBuR** [comment] 2023-11-22 08:32
Thanks for moving it, you a right, the result is similar but the cause is completely different.

Link to the game: https://lichess.org/eN0MpXmc (my bot is black)

Full logs of the game:

```
Engine:  26...  Nc5        0.00     48/48      Nodes:     1       NPS:     1                                         TB:     1

Engine:  27...  Ne6       +0.08     32/50      Nodes:   4.3 M     NPS:   1.1 M     MT: 00:03.8     Hash:   9.2 %     TB:    79

Engine:  28...  Nxg5      +0.16     32/46      Nodes:   4.3 M     NPS:   1.2 M     MT: 00:03.7     Hash:   9.8 %     TB:   100

Engine:  29...  Ne6       +0.08     39/46      Nodes:  25.3 M     NPS:   1.1 M     MT: 00:23.2     Hash:  56.3 %     TB:   993

Engine:  30...  Rd8       +0.12     39/47      Nodes:   5.1 M     NPS:   1.1 M     MT: 00:04.7     Hash:  11.7 %     TB:   113

Engine:  31...  Nxd8      +0.09     35/52      Nodes:   8.7 M     NPS:   1.1 M     MT: 00:08.0     Hash:  22.1 %     TB:   259

________________________________________________________________________________________________________________________________

ID: nD43xgWa     Challenger: BOT mayhem23111 (2934)     TC: 5+5     Rated     Color: Random     Variant: Standard

Challenge added to queue.

‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾

Engine:  32...  Rc4       +0.48     36/34      Nodes:   3.2 M     NPS:   1.1 M     MT: 00:02.9     Hash:   6.4 %     TB:     2

Engine:  33...  Rxa4      +1.36     23/40      Nodes:   3.4 M     NPS:   1.1 M     MT: 00:03.1     Hash:   8.0 %     TB:   108

Exception in thread Thread-913:

Traceback (most recent call last):

  File "/usr/local/lib/python3.12/threading.py", line 1052, in _bootstrap_inner

    self.run()

  File "/game.py", line 71, in run

    updated = self.lichess_game.update(event)

              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/lichess_game.py", line 88, in update

    self.board.push(chess.Move.from_uci(moves[-1]))

  File "/usr/local/lib/python3.12/site-packages/chess/__init__.py", line 2259, in push

    assert piece_type is not None, f"push() expects move to be pseudo-legal, but got {move} in {self.board_fen()}"

AssertionError: push() expects move to be pseudo-legal, but got a1a4 in 3n2k1/2p2ppp/1p6/8/r2BP3/2P2PP1/5K2/5R2

________________________________________________________________________________________________________________________________ArasanX will not be challenged to a new game pair before 2023-11-22 08:33:16.
``

**Comment by Torom** [comment] 2023-11-22 08:46
To be honest, I would just blame it on the Lichess reboot that was done at the time. ToromBot also got stuck, which normally doesn't happen very often anymore. RaspFish continues to run normally.

I would be interested to know what the `gameState` event looked like that could cause this error. The push to the local board is only executed if more moves are sent than those we already know (because our own move is also sent to us again, but we already push it to the local board ourselves). So Lichess must have sent more moves than we knew and yet the newest move in this list is the one we just played ourselves `a1a4`. Which in turn triggers the error, because another `a1a4` is of course not possible in the position after `a1a4`.

**Comment by Torom** [comment] 2023-11-22 08:48
Ah no, we're black, then that's not true.

**Comment by IbaiBuR** [comment] 2023-11-22 08:49
Yes my bot is black, I think the Lichess reboot has probably something to do with it too

**Comment by Torom** [comment] 2023-11-22 09:07
So it looks like we got a `gameState` event with `34. Rf1` (which neither makes sense nor is really played in the game) and then a `gameState` event with `34. Rxa4` which then of course cannot be executed on our local board.

Very interesting but probably caused by the Lichess reboot, as long as it doesn't happen again I'd say it's not a problem.

**Comment by IbaiBuR** [comment] 2023-11-22 09:10
Yes, quite weird so far, I was watching the game live and I was shocked when I saw my engine giving a rook for free somehow, which made absolutely no sense.

I know BotLi does not make up the moves, thats why I was surprised.

So yeah, I think this is solely because of the lichess update because if not I cant find the reason.

**Comment by IbaiBuR** [comment] 2023-11-22 09:11
> Edit: On the other hand, we would have had to make a move after the imaginary `34. Rf1`, which didn't happen. So I don't know what happened.

After the error BotLi ignored the game and started matchmaking again, so I guess that is why there were 2 instances of the engine running

**Comment by Torom** [comment] 2023-11-22 09:13
Well, for `33... Rxa4` I don't really see any other reason than the engine just wanted to play it. What's normally your NPS? That's usually the best way to recognize a second engine, as the NPS is then roughly halved.

**Comment by IbaiBuR** [comment] 2023-11-22 09:14
In the game the NPS were normal (1.2M which is what I normally get with 2 threads), the second instance was launched after the error.

**Comment by Torom** [comment] 2023-11-22 09:16
That's what I thought. BotLi does not terminate the engine correctly when an error occurs, I would probably have to solve that better.

**Comment by IbaiBuR** [comment] 2023-11-22 09:29
I see :)

At least we were able to spot where the problem was, still very weird though

**Closed** 2023-11-24 20:25 UTC
Labels: bug
