### ISSUE TITLE
!eval and !printeval command reformat

### ISSUE THREAD

**Issue by FatFritz2** [Torom/BotLi#143] opened 2023-09-18 16:48 UTC
Hi @Torom 
I want to reformat the !eval and !printeval format from
Old format: `0.05 33/39 Nodes: 6.3 M NPS: 1.5 M MT: 00:04.3 Hash: 4.0 % PV: 53. Rh8 Rc2 54. b7 Nc6 55. Rc8 Ra2+ 56. Kb5 Nxe5`
To this lichess-bot format:  `Source: Engine, Evaluation: -0.08, Winrate: 49.8%, Depth: 20, Nodes: 669.5K, Speed: 1.0Mnps, Pv: 26...Bxc5 27. Be1 Nb4 28. Bxb4 Rxb4 29. a5`
In my opinion, I think the lichess-bot format is clearly better for me since it supports UCI_WDL feature, clear expressions and If you reformat it i really hope you add the hash info right after the Speed and I think you can put the Move time to the very last just before the PV 

Thats my idea
Thanks

**Comment by Torom** [comment] 2023-09-18 16:52
duplicate of #142

**Closed by Torom** 2023-09-18 16:52 UTC
Labels: enhancement
